In [2]:
import pandas as pd
import numpy as np
import pdfplumber
import re

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
import os

folder_path = "resumes"

files = os.listdir(folder_path) # List all files in the folder

for file in files:
    full_path = os.path.join(folder_path, file)
    print(full_path)

resumes\Abiral_Pandey_Fullstack_Java.docx
resumes\Achyuth Resume_8.docx
resumes\Adelina_Erimia_PMP1.docx
resumes\Adhi Gopalam - SM.docx
resumes\AjayKumar.docx
resumes\Akhil.profile.docx
resumes\Akhil_Sr BSA.docx
resumes\Alekhya Resume.docx
resumes\Amar Sr BSA.docx
resumes\Ami Jape.docx
resumes\Amrinder Business Analyst.docx
resumes\Amulya Komatineni.docx
resumes\Anil Krishna Mogalaturthi.docx
resumes\AnilAgarwal.docx
resumes\Anudeep N_Sr Java Developer.docx
resumes\Ashok Jayakumar - PM.docx
resumes\Ashwini J2EE Developer.docx
resumes\Atul_Mathur_Resume.docx
resumes\Avathika BA-Healthcare_.docx
resumes\avinash G.docx
resumes\B Shaker-Sr BSA-Scrum Master .docx
resumes\B Suresh Kumar_Project Manager_1.docx
resumes\BA - Abhishek.docx
resumes\BA - Navneet.docx
resumes\BA Kiran.docx
resumes\BA with INV.docx
resumes\Balaji Gopalakrishnan Project Manager.docx
resumes\Balakrishna Sudabathula.docx
resumes\Bapuji Hadoop developer.docx
resumes\Bharat Arora_CV_PMP _ ERP1.docx
resumes\Bharatha BA Resume.docx
resumes\Brahma-Resume (BA).docx
resumes\Business Analyst_GHyma.docx
resumes\Chandler_BA.docx
resumes\chenna kesava.docx
resumes\CHETAN_Sr Java Developer.docx
resumes\Dantu Padmasri - Project Manager.docx
resumes\Dave.docx
resumes\Deepika Chintalapati.docx
resumes\Deepika DC.docx
resumes\Derik.docx
resumes\Dhanalaxmi -BA.docx
resumes\Drakshajavauidev.docx
resumes\employer_mounika details.docx
resumes\Francis Gomes Resume.docx
resumes\Gautami Bulusu Mobile Testing 3.docx
resumes\Gokul Selvam S PM.docx
resumes\Gopi.docx
resumes\Gururaja Murthy PMCPCSM.docx
resumes\Haarika_BA.docx
resumes\Harika_java.docx
resumes\Harish K.docx
resumes\harish S.docx
resumes\HARI_Sr.Java Developer.docx
resumes\Harshitha Challa.docx
resumes\indrakaran soma.docx
resumes\jagadeesh k.docx
resumes\Jagan S Iyer PM.docx
resumes\Jaya prakash.docx
resumes\Jayadattaperi N.docx
resumes\jeck P.docx
resumes\Jennifer  M. Conte.docx
resumes\Jimi_Desai_PM.docx
resumes\kalyan das.docx
resumes\Kashyap K. Vora resume.docx
resumes\KIRAN KUMAR.docx
resumes\komal patel.docx
resumes\Komala BSA Resume.docx
resumes\Krishna Kuruvella.docx
resumes\Krishna Sr. BSA Resume.docx
resumes\Krishnapriya_BA.docx
resumes\Krishna_BSA.docx
resumes\Krishna_SrJava.docx
resumes\Kumar Raj.docx
resumes\Kuppurajbabu_BA.docx
resumes\KY BA PM UPDATED RESUME .docx
resumes\Madhuri Pawar.docx
resumes\madhuri R.docx
resumes\madhuri_java.docx
resumes\Madhu_BA_AW.DOCX
resumes\mahesh_Java.docx
resumes\Mahesh_Kamath_PM (1).docx
resumes\Manikanta P.docx
resumes\manish_singh_resume.docx
resumes\Mani_Hadoop.docx
resumes\Manohar B.docx
resumes\Manohar Reddy.docx
resumes\manohar.B.docx
resumes\Mehul.docx
resumes\Mitali Barman_Resume.docx
resumes\Mohamad Jamil.docx
resumes\Mohammad Resume.docx
resumes\mohid_rj.docx
resumes\mounika BA resume 7.docx
resumes\Mounika health care resume.docx
resumes\MounikaReddy.docx
resumes\Mounika_P.docx
resumes\Murali_Project Manager QA.DOCX
resumes\Nandini_Resume.docx
resumes\Naren Sr.BA .docx
resumes\Naren Sr.BA.docx
resumes\Naresh V.docx
resumes\Naveen Arora.docx
resumes\Naveen Kumar Bandela.docx
resumes\Naveen.S_Resume.docx
resumes\Navneeth Resume.docx
resumes\Neha Mugghala.docx
resumes\Nikhil.docx
resumes\Nikith Reddy.docx
resumes\Nikki_Nimmagadd.docx
resumes\Nilesh-resume_1_phplead.docx
resumes\Niteesh Java Developer.docx
resumes\nithin katapally.docx
resumes\nithin Reddy.docx
resumes\Othman - Project Manager.docx
resumes\Pankaj BSA.docx
resumes\ParthMPatel_BA.docx
resumes\Pavan Kumar Full Stack Java Developer.docx
resumes\Pavan Sr Business Analyst resume.docx
resumes\Pierre John.docx
resumes\PM RESUME.docx
resumes\Pranay P.docx
resumes\Prashant Chawda_resume.docx
resumes\Praveen B.docx
resumes\Praveen T.docx
resumes\Priya B.docx
resumes\Priyanka Sr BSA Resume.docx
resumes\Priya_Sharma.docx
resumes\Raja Santhosam_PM Scrum Master.DOCX
resumes\Rajendra-PMP-CSM.docx
resumes\Rajesh_k.docx
resumes\Raju Goduguchinta_Technical Program Manager.docx
resumes\ram krishna.docx
resumes\ram nandyala.docx
resumes\Ramachandra EDA.docx
resumes\Ramteja Motupalli.docx
resumes\RAMYA BUSINESS ANALYST RESUME.docx
resumes\Randy Adams.docx
resumes\Ranjan_Project Manager-Scrum Master.docx
resumes\Rao_Java.docx
resumes\Rashmitha R.docx
resumes\Ravi Pattar- Sr. Agile Program manager.docx
resumes\Ravi Reddy.docx
resumes\RaviBurra_Certified PM_DevOps.docx
resumes\ravikiran JALASUTRAPU.docx
resumes\RaviRaju_Resume.docx
resumes\Reddemma_Lankipalle.docx
resumes\Resume - Kishore Kotapati - 218E - BA.docx
resumes\Resume - PM Agile-Scrum.docx
resumes\Resume - Sr PM.docx
resumes\Resume Vishal PM - MSIS, PMP-PMI.docx
resumes\Resume2018March.docx
resumes\Resume_Spoorti Pandit_BSA.docx
resumes\Robinson.docx
resumes\Rohanu Resume.docx
resumes\ronith s.docx
resumes\Sahas BA Resume.docx
resumes\Sahithi K.docx
resumes\sai k.docx
resumes\Sai Krishna BA.docx
resumes\Sai kumar.docx
resumes\Sai Srinivas_Sr_Java_Developer.docx
resumes\sairithvik alla.docx
resumes\Saiteja G.docx
resumes\Samir Naik-NJ - Feb 2018-V6.0.docx
resumes\Samir Naik-NJ - Mar 2018-V3.0.docx
resumes\sanjay kumar.docx
resumes\Santosh Arugula BA.docx
resumes\Sarath M.docx
resumes\SaravanaKumar.docx
resumes\Satish Reddy.docx
resumes\Satish Uduta.docx
resumes\SAURABH_PM.docx
resumes\Shail_Tank-Business Analyst .docx
resumes\Shaker Resume.docx
resumes\Sharath Java.docx
resumes\Shashank.docx
resumes\Shelly Woods.docx
resumes\Shiuli Mahmud.docx
resumes\Shiva G-Java Resume.docx
resumes\Siddhartha Gandroju.docx
resumes\Smita Kamble_Resume.docx
resumes\Sougandh_Java Fullstack Developer.docx
resumes\Spoorthi Finance BSA Resume.docx
resumes\Sr. Business Analyst.docx
resumes\Sravani Battu.docx
resumes\Sravani Singirikonda.docx
resumes\Sri Gati.docx
resumes\srinivas b.docx
resumes\Srivatsan_Project_Manager.docx
resumes\Sudhakar Reddy.docx
resumes\Sumanth Manne Java Developer.docx
resumes\Sundar_Java_8+ Years..docx
resumes\SUNITHA Project Manager (1).docx
resumes\Syed_Zia_Ashraf.docx
resumes\Tanmay_Dam_Resume_BA.docx
resumes\Tarun RESUME-BSAT.docx
resumes\Tarun Resume.docx
resumes\Tarun.docx
resumes\Tarun_Developer.docx
resumes\Tejaswi-resume.docx
resumes\TeresaNeetipudi IT BA.DOCX
resumes\Tushar Patel.docx
resumes\Uday_Maripelly.docx
resumes\Ujvala BA Feb 20.docx
resumes\Utthan Silawal12.docx
resumes\V Ashok A.docx
resumes\Vamshi L.docx
resumes\Vamshi Teja_Business Analyst.docx
resumes\Varun Kumar.docx
resumes\Varun.docx
resumes\vema reddy.docx
resumes\Venkata_Sr.PHP_Developer.docx
resumes\Venkat_BA.docx
resumes\venu b.docx
resumes\Vijay Bhargav.docx
resumes\VIJETHA G.docx
resumes\vikas java.docx
resumes\Vikash_BA_Ab.docx
resumes\Vinay.D_Resume.docx
resumes\Vishal S..docx
resumes\Vishnu BA Resume.docx
resumes\Vishnu J.docx
resumes\Vishnu Java dev.docx
resumes\Vivek Joshi_CV.docx
resumes\Vivek.BSA.docx
resumes\Yohan BSA.docx
resumes\Yugesh_Resume.docx

In [8]:
from docx import Document
import pdfplumber
import os

def extract_text(file_path):
    if file_path.endswith(".docx"):
        doc = Document(file_path)
        return " ".join([p.text for p in doc.paragraphs]) # Extract text from .docx files

folder = "resumes"
data = []

for file in os.listdir(folder):
    path = os.path.join(folder, file)
    text = extract_text(path)
    data.append(text)

print(len(data), "resumes loaded")
print(data[0][:500]) # Print the first 500 characters of the first resume to verify extraction

228 resumes loaded
Name: Abiral Pandey Email: abiral.pandey88@gmail.com Phone: 940-242-3303 Current Location: Woonsocket, Rhode Island Visa Status: US Citizen  SUMMARY: Dynamic individual with 6 years of software development experience in design, development, deployment, maintenance, production and support of web - based and Client-Server business applications using OOP and Java/J2EE technologies. Exposure to all phases of Software Development Life Cycle(SDLC) using Agile, RUP, Waterfall. Designed and developed we

In [10]:
df = pd.DataFrame({
    "Resume_Text": data
}) # Create a DataFrame with the extracted resume texts 

df.head(10)

                                         Resume_Text
0  Name: Abiral Pandey Email: abiral.pandey88@gma...
1  Achyuth 540-999-8048 achyuth.java88@gmail.com ...
2  Adelina Erimia, PMP, Six Sigma Green Belt, SMC...
3  Adhi Gopalam adhigopalam@gmail.com 281-212-359...
4  Ajay Kumar (CSM)\t     \t\t     Email/Skype: a...
5  Akhil                                         ...
6  Akhil                                         ...
7  Alekhya (515)-518-0849 alekhya.workmail@gmail....
8  Amar Amar.srbsa@gmail.com       Phone : 201-70...
9  Ami Jape 50 GRAHAM ST, JERSEY CITY NJ 07307 Am...

In [12]:
import re

def clean_text(text):
    if not isinstance(text, str):
        return ""   # safely handle None / NaN
    text = text.lower()
    text = re.sub(r'\n+', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    return text # Clean the text by lowercasing, removing newlines, extra spaces, and special characters

df['Cleaned_Text'] = df['Resume_Text'].apply(clean_text)
df.head(10)# Check the cleaned text to ensure it's properly processed

,Resume_Text,Cleaned_Text
0,Name: Abiral Pandey Email: abiral.pandey88@gma...,name abiral pandey email abiralpandey88gmailco...
1,Achyuth 540-999-8048 achyuth.java88@gmail.com ...,achyuth 5409998048 achyuthjava88gmailcom objec...
2,"Adelina Erimia, PMP, Six Sigma Green Belt, SMC...",adelina erimia pmp six sigma green belt smc 46...
3,Adhi Gopalam adhigopalam@gmail.com 281-212-359...,adhi gopalam adhigopalamgmailcom 2812123592 ce...
4,Ajay Kumar (CSM)\t \t\t Email/Skype: a...,ajay kumar csm emailskype ajaydtgmailcom mob 1...
5,Akhil ...,akhil sr business systems analyst akhilmohan01...
6,Akhil ...,akhil sr business systems analyst akhilmohan01...
7,Alekhya (515)-518-0849 alekhya.workmail@gmail....,alekhya 5155180849 alekhyaworkmailgmailcom pro...
8,Amar Amar.srbsa@gmail.com Phone : 201-70...,amar amarsrbsagmailcom phone 2017088565 busin...
9,"Ami Jape 50 GRAHAM ST, JERSEY CITY NJ 07307 Am...",ami jape 50 graham st jersey city nj 07307 ami...

In [14]:
job_description = input("Enter the job description: ").strip() # Get the job description from the user and strip leading/trailing whitespace

In [ ]:
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity # Import necessary libraries for generating embeddings and calculating similarity

model = SentenceTransformer('all-MiniLM-L6-v2') # Load the pre-trained SentenceTransformer model for generating embeddings

job_emb = model.encode(job_description) # Generate the embedding for the job description using the model
resume_embs = model.encode(df['Cleaned_Text'].tolist()) # Generate embeddings for all cleaned resume texts using the model

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
c:\Users\Asus-2025\Downloads\Machine Learning Concepts and Projects\.venv\lib\site-packages\huggingface_hub\file_download.py:138: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Asus-2025\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 4069.03it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [24]:
scores = cosine_similarity(resume_embs, [job_emb]).flatten() # Calculate cosine similarity scores between each resume embedding and the job description embedding

df['NLP_Score'] = scores 
df_sorted = df.sort_values(by='NLP_Score', ascending=False) # Sort the DataFrame by the NLP similarity scores in descending order
print(df_sorted[['NLP_Score']].head(10)) # Print the top 10 resumes with their NLP similarity scores to the job description

     NLP_Score
26    0.423790
213   0.408815
27    0.381791
219   0.369813
110   0.369075
38    0.364288
203   0.361337
176   0.358674
188   0.358156
92    0.355583

In [25]:
required_skills = ["python", "machine learning", "sql"]

def skill_score(text):
    return sum(skill in text for skill in required_skills) / len(required_skills)

df['Skill_Score'] = df['Cleaned_Text'].apply(skill_score)# Calculate a skill score based on the presence of required skills in the cleaned resume text
df_sorted = df.sort_values(by=['NLP_Score', 'Skill_Score'], ascending=False) # Sort by NLP score and then by skill score
print(df_sorted[['NLP_Score', 'Skill_Score']].head(10))

     NLP_Score  Skill_Score
26    0.423790     0.333333
213   0.408815     0.333333
27    0.381791     0.333333
219   0.369813     0.333333
110   0.369075     0.333333
38    0.364288     0.333333
203   0.361337     0.333333
176   0.358674     0.333333
188   0.358156     0.333333
92    0.355583     0.333333

In [26]:
df['Final_Score'] = 0.7 * df['NLP_Score'] + 0.3 * df['Skill_Score'] # Combine NLP score and skill score into a final score with weights
df_sorted = df.sort_values(by='Final_Score', ascending=False) # Sort by the final combined score
print(df_sorted[['Final_Score', 'NLP_Score', 'Skill_Score']     ].head(10)) # Print the top 10 resumes with their final scores, NLP scores, and skill scores

     Final_Score  NLP_Score  Skill_Score
64      0.537737   0.339624     1.000000
170     0.507913   0.297019     1.000000
215     0.500714   0.286734     1.000000
86      0.497022   0.281460     1.000000
211     0.476110   0.251586     1.000000
73      0.445897   0.351281     0.666667
212     0.437707   0.339581     0.666667
87      0.436109   0.337299     0.666667
141     0.429852   0.328360     0.666667
84      0.420432   0.314902     0.666667

In [27]:
def explain(text):
    matched = [s for s in required_skills if s in text]
    missing = [s for s in required_skills if s not in text]
    return matched, missing
# Apply the explain function to each cleaned resume text to get matched and missing skills, and store them in new columns
df[['Matched', 'Missing']] = df['Cleaned_Text'].apply(lambda x: pd.Series(explain(x))) 
print(df[['Matched', 'Missing']].head(10))

         Matched                          Missing
0          [sql]       [python, machine learning]
1  [python, sql]               [machine learning]
2             []  [python, machine learning, sql]
3             []  [python, machine learning, sql]
4          [sql]       [python, machine learning]
5          [sql]       [python, machine learning]
6          [sql]       [python, machine learning]
7          [sql]       [python, machine learning]
8          [sql]       [python, machine learning]
9          [sql]       [python, machine learning]

In [32]:
df['Decision'] = df['Final_Score'].apply(lambda x: "Selected" if x > 0.5 else "Rejected") # Make a simple decision based on the final score with a threshold
print(df[['Final_Score', 'Decision']].head(50)) # Print the final scores and decisions for the top 10 resumes

    Final_Score  Decision
0      0.232515  Rejected
1      0.337434  Rejected
2      0.108048  Rejected
3      0.116620  Rejected
4      0.249595  Rejected
5      0.188505  Rejected
6      0.186389  Rejected
7      0.243852  Rejected
8      0.209441  Rejected
9      0.208585  Rejected
10     0.272101  Rejected
11     0.255798  Rejected
12     0.307544  Rejected
13     0.298412  Rejected
14     0.210354  Rejected
15     0.241187  Rejected
16     0.157270  Rejected
17     0.201443  Rejected
18     0.281606  Rejected
19     0.202995  Rejected
20     0.266959  Rejected
21     0.368964  Rejected
22     0.280494  Rejected
23     0.305630  Rejected
24     0.262581  Rejected
25     0.222400  Rejected
26     0.396653  Rejected
27     0.367253  Rejected
28     0.348669  Rejected
29     0.298077  Rejected
30     0.323398  Rejected
31     0.370827  Rejected
32     0.326558  Rejected
33     0.309335  Rejected
34     0.351852  Rejected
35     0.242010  Rejected
36     0.263145  Rejected
37     0.378080  Rejected
38     0.355001  Rejected
39     0.269276  Rejected
40     0.378080  Rejected
41     0.216435  Rejected
42     0.237763  Rejected
43     0.059531  Rejected
44     0.163832  Rejected
45     0.316148  Rejected
46     0.246305  Rejected
47     0.363257  Rejected
48     0.198110  Rejected
49     0.310614  Rejected